# Generated by Django 5.1.2 on 2024-11-12 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500, verbose_name='出典')),
                ('quiz_text', models.TextField(max_length=1000, verbose_name='クイズ')),
                ('correct', models.CharField(max_length=100, verbose_name='正解')),
                ('incorrect_1', models.CharField(max_length=100, verbose_name='不正解1')),
                ('incorrect_2', models.CharField(max_length=100, verbose_name='不正解2')),
            ],
        ),
    ]
