# Generated by Django 5.1.2 on 2024-11-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='source_text',
            field=models.TextField(default='', max_length=5000, verbose_name='出典元本文'),
        ),
    ]
